- hosts: localhost
  become: true
  pre_tasks:
    - name: update cache
      dnf:
        update_cache: true
      tags:
        - zsh
        - neovim
  tasks:
  - include: zsh.yaml
  - include: neovim.yaml
